version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_bridge_net
  redis:
    image: redis:3.2.0
    networks:
      - my_bridge_net
  networks:
    my_bridge_net:
      driver: bridge
